/**
 * Single source of truth for the app version shown in the UI.
 *
 * GENERATED by scripts/sync-version.mjs from package.json — do not edit by
 * hand (run `npm run sync:version` or just build). In the packaged desktop
 * app, `window.electronAPI.getVersion()` returns the real Electron version
 * and is always preferred; this constant is the browser/dev fallback.
 */
export const APP_VERSION = "1.4.0-beta.7";
