/**
 * فاز ۷.۴ — generate src/lib/version.ts from package.json so the version
 * lives in exactly ONE place. Wired into `npm run build` (before next build).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath (NOT .pathname) — .pathname keeps the "/D:/..." leading slash
// on Windows and path.resolve then prepends the drive again ("D:\D:\..."),
// which broke the GitHub Actions Windows runner (beta.2 CI failure).
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = pkg.version;

const out = `/**
 * Single source of truth for the app version shown in the UI.
 *
 * GENERATED by scripts/sync-version.mjs from package.json — do not edit by
 * hand (run \`npm run sync:version\` or just build). In the packaged desktop
 * app, \`window.electronAPI.getVersion()\` returns the real Electron version
 * and is always preferred; this constant is the browser/dev fallback.
 */
export const APP_VERSION = "${version}";
`;

const target = path.join(root, "src", "lib", "version.ts");
const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
if (current !== out) {
  fs.writeFileSync(target, out, "utf8");
  console.log("version.ts ->", version);
} else {
  console.log("version.ts already in sync:", version);
}
